imports:
- { resource: parameters.yml }
- { resource: security.yml }
- { resource: services.yml }
- { resource: "@Project3WebsiteBundle/Resources/config/services.yml" }

parameters:
    locale: "nl"

framework:
    test: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        logo_lg_img: 'bundles/project3website/images/food-guru-logo-big.png'
        logo_lg_alt: 'FoodGuru logo big'
        logo_med_img: 'bundles/project3website/images/food-guru-logo-medium.png'
        logo_med_alt: 'FoodGuru logo medium'

# Doctrine Configuration
doctrine:
    dbal:
        driver: 'pdo_mysql'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_admin:
    title: 'FoodGuru'
    options:
        title_mode: "single_text"
    persist_filters: true

fm_elfinder:
    instances:
        default:
            locale: '%locale%'
            editor: form
            theme: smoothness
            include_assets: true
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 8M

fos_elastica:
    clients:
        default: { host: project3.local, port: 9200 }
    indexes:
        src:
            settings:
                index:
                    analysis:
                        analyzer:
                            name_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [standard, lowercase, asciifolding, elision]
            types:
                gerecht:
                    mappings:
                        categorie: ~
                        stappen: ~
                        ingredienten: ~
                        id: ~
                        naam: ~
                        foto: ~
                        beschrijving: ~
                        rating: ~
                        actief: ~
                        benodigdheden: ~
                        bereidingstijd: ~
                        name_suggest:
                            type: completion
                            analyzer: name_analyzer
                            search_analyzer: name_analyzer
                            payloads: true

                    persistence:
                        driver: orm
                        model: Project3\WebsiteBundle\Entity\Gerecht
                        provider: ~
                        finder: ~

fos_user:
    db_driver: 'orm'
    firewall_name: 'main'
    user_class: 'Project3\WebsiteBundle\Entity\User'
    group:
        group_class: 'Project3\WebsiteBundle\Entity\Group'
    service:
        mailer: fos_user.mailer.noop
    from_email:
        address: 'robbertluit@hotmail.com'
        sender_name: 'Robbert'
