project3_admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

project3_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

project3_website:
    resource: "@Project3WebsiteBundle/Resources/config/routing.yml"
    prefix:   /

