# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_USER:        [ROLE_SONATA_ADMIN]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
              providers: [hardcoded, database]
        hardcoded:
            memory:
              users:
                  robbert: { password: "000000", roles: ['ROLE_SUPER_ADMIN'] }
                  phedra: { password: "000000", roles: ['ROLE_SUPER_ADMIN'] }
        database:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
              login_path: project3_security_login
              check_path: project3_security_login
            logout:
              path: project3_security_logout
            remember_me:
              secret:   '%secret%'
              lifetime: 604800 # 1 week
              path:     /

    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/account, roles: ROLE_USER }
#      - { path: ^/, roles: ROLE_USER }
