#HOME - INDEX
project3_website_home:
    path:     /
    defaults: { _controller: Project3WebsiteBundle:Default:index }
project3_website_contact:
    path:     /contact
    defaults: { _controller: Project3WebsiteBundle:Default:contact }





#ACCOUNT
project3_account_instellingen:
    path:     /account/instellingen
    defaults: { _controller: Project3WebsiteBundle:Account:instellingen}

project3_account_shoppinglijstjes:
    path:     /account/shoppinglijstjes
    defaults: { _controller: Project3WebsiteBundle:Account:shoppinglijstjes }

project3_account_klaargemaakte_gerechten:
    path:     /account/klaargemaakte-gerechten
    defaults: { _controller: Project3WebsiteBundle:Account:klaargemaakteGerechten }





#GERECHTEN
project3_klaargemaakt_new:
    path:     gerechten/gerecht/{id}/klaargemaakt
    defaults: { _controller: Project3WebsiteBundle:Account:klaargemaakteGerechten}
    methods: [GET,POST]

project3_alle_gerechten:
    path:     /gerechten
    defaults: { _controller: Project3WebsiteBundle:Gerecht:overzicht}

project3_gerecht_detail:
    path:     /gerechten/gerecht/{id}
    defaults: { _controller: Project3WebsiteBundle:Gerecht:detail, id: id}

project3_gerecht_query:
    path:     /gerechten/zoek/
    defaults: { _controller: Project3WebsiteBundle:Gerecht:query}





#CONTACT / EMAIL
project3_contact_show:
    path:     /contact/{id}/
    defaults: { _controller: Project3WebsiteBundle:Contact:show}
    methods: [GET]

project3_contact_new:
    path:     /contact/create/new/
    defaults: { _controller: Project3WebsiteBundle:Contact:new}
    methods: [GET,POST]

project3_contact_edit:
    path:     /contact/edit/{id}
    defaults: { _controller: Project3WebsiteBundle:Contact:edit}
    methods: [GET,POST]

project3_contact_delete:
    path:     /contact/delete/{id}
    defaults: { _controller: Project3WebsiteBundle:Contact:delete}



#SHOPPINGLIJST
shoppinglist_add:
    path:     /addshoppinglist
    defaults: { _controller: Project3WebsiteBundle:Shoppinglist:addToShoppinglist }
    methods: [POST]



#MAIL
project3_mail:
    path:     /mail/{id}
    defaults: { _controller: Project3WebsiteBundle:Gerecht:mail }
    methods: [GET,POST]


#EXTRA
project3_website_group:
    path:     /group/{slug}
    defaults: { _controller: Project3WebsiteBundle:Default:group, slug: null }
