#HOME - INDEX
project3_website_home:
    path:     /
    defaults: { _controller: Project3WebsiteBundle:Default:index }

#ACCOUNT
project3_account_instellingen:
    path:     /account/instellingen
    defaults: { _controller: Project3WebsiteBundle:Account:instellingen}

project3_account_shoppinglijstjes:
    path:     /account/shoppinglijstjes
    defaults: { _controller: Project3WebsiteBundle:Account:shoppinglijstjes }

project3_account_klaargemaakte_gerechten:
    path:     /account/klaargemaakte-gerechten
    defaults: { _controller: Project3WebsiteBundle:Account:klaargemaakteGerechten }

#GERECHTEN
project3_alle_gerechten:
    path:     /gerechten
    defaults: { _controller: Project3WebsiteBundle:Gerecht:overzicht}

project3_gerecht_detail:
    path:     /gerechten/gerecht/{id}
    defaults: { _controller: Project3WebsiteBundle:Gerecht:detail, id: id}

project3_gerecht_surprise:
    path:     /gerechten/verrassing
    defaults: { _controller: Project3WebsiteBundle:Gerecht:surprise}

project3_gerecht_query:
    path:     /gerechten/{query}
    defaults: { _controller: Project3WebsiteBundle:Gerecht:query, query: query}








#EXTRA
project3_website_group:
    path:     /group/{slug}
    defaults: { _controller: Project3WebsiteBundle:Default:group, slug: null }
