project3_security_login:
    path:     /login
    defaults: { _controller: Project3WebsiteBundle:Security:login }

project3_security_logout:
    path:     /logout
    defaults: { _controller: Project3WebsiteBundle:Security:logout }

project3_security_register:
    path:     /register
    defaults: { _controller: Project3WebsiteBundle:Security:register }

admin_dashboard:
    path:     /admin/dashboard
