services:

    project3_website.service.database:
        class:     Project3\WebsiteBundle\Service\Database
        arguments: ["@service_container"]

    project3_website.twig.extensions:
        class:     Project3\WebsiteBundle\Twig\Extensions
        arguments: ["@project3_website.service.database"]
        tags:
            - { name: twig.extension }

    project3_website.admin.group:
        class: Project3\WebsiteBundle\Admin\GroupAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Group, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: Group }

    project3_website.admin.user:
        class: Project3\WebsiteBundle\Admin\UserAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: User }

    project3_website.admin.recept:
        class: Project3\WebsiteBundle\Admin\ReceptAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Recept, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: FoodGuru, label: Recept }
        public: true

    project3_website.admin.ingredient:
        class: Project3\WebsiteBundle\Admin\IngredientAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Ingredient, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: FoodGuru, label: Ingredient }
        public: true

    project3_website.admin.stap:
        class: Project3\WebsiteBundle\Admin\StapAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Stap, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: FoodGuru, label: Stap }
        public: true

    project3_website.admin.block:
        class: Project3\WebsiteBundle\Admin\BlockAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Block, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: FoodGuru, label: Block }
        public: true

    project3_website.admin.pagina:
        class: Project3\WebsiteBundle\Admin\PaginaAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Pagina, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: FoodGuru, label: Pagina }
        public: true
