services:

    project3_website.service.database:
        class:     Project3\WebsiteBundle\Service\Database
        arguments: ["@service_container"]

    project3_website.twig.extensions:
        class:     Project3\WebsiteBundle\Twig\Extensions
        arguments: ["@project3_website.service.database"]
        tags:
            - { name: twig.extension }

#GROUPS
    project3_website.admin.group:
        class: Project3\WebsiteBundle\Admin\GroupAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Group, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: Group }
    #USERS
    project3_website.admin.user:
        class: Project3\WebsiteBundle\Admin\UserAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: User }

    #PAGINA'S
    project3_website.admin.pagina:
        class: Project3\WebsiteBundle\Admin\PaginaAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Pagina, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pagina's, label: Pagina }
        public: true

    #BLOKKEN
    project3_website.admin.block:
        class: Project3\WebsiteBundle\Admin\BlockAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Block, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pagina's, label: Blokken }
        public: true

    #GERECHTEN
    project3_website.admin.gerecht:
        class: Project3\WebsiteBundle\Admin\GerechtAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Gerecht, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gerechten, label: Gerecht }
        public: true

    #INGREDIENTEN
    project3_website.admin.ingredient:
        class: Project3\WebsiteBundle\Admin\IngredientAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Ingredient, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gerechten, label: Ingredienten }
        public: true

    #STAPPEN
    project3_website.admin.stap:
        class: Project3\WebsiteBundle\Admin\StapAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Stap, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gerechten, label: Stappen }
        public: true

    #CATEGORIES
    project3_website.admin.categorie:
        class: Project3\WebsiteBundle\Admin\CategorieAdmin
        arguments: [~, Project3\WebsiteBundle\Entity\Categorie, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Gerechten, label: Categorie }
        public: true
