<?php

namespace Project3\WebsiteBundle\Repository;

/**
 * GerechtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GerechtRepository extends \Doctrine\ORM\EntityRepository
{
}
