<?php

namespace Project3\WebsiteBundle\Repository;

/**
 * Klaargemaakte_gerechtenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Klaargemaakte_gerechtenRepository extends \Doctrine\ORM\EntityRepository
{
}
