<?php

namespace Project3\WebsiteBundle\Repository;

/**
 * ShoppinglijstRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppinglijstRepository extends \Doctrine\ORM\EntityRepository
{
}
